language: cpp

dist: trusty

compiler:
      - g++

env:
    addons:
        apt:
            packages:
                - g++-5

before_install:
    - sudo apt-get install liblua5.2-dev

#before_script:
      #- cd howto/lua-example

script:
    - make
    #- make run
