language: generic

dist: trusty

os: linux

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test


before_install:
    - sudo apt-get install liblua5.2-dev

before_script:
    - g++-5 --version
      #- cd howto/lua-example

script:
    - make
    #- make run
